// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ItemWrapper.Generator
{
    using System.Linq;
    using System;
    
    
    #line 1 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class GeneratorTableDefinition : Transformation
    {
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
        public override string TransformText()
        {
            this.GenerationEnvironment = null;
            this.Write("\t// Defines the shape of the table ");
            
            #line 3 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\tinternal partial struct ");
            
            #line 4 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data {\r\n");
            
            #line 5 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

foreach(Column column in this.Table.Columns) {
	if(string.IsNullOrEmpty(column.Check)) {

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 9 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 9 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 10 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
	} else {
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 11 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" field");
            
            #line 11 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\tpublic ");
            
            #line 12 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 12 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\tget { return this.field");
            
            #line 13 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("; }\r\n\t\t\tset { this.field");
            
            #line 14 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 14 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Check));
            
            #line default
            #line hidden
            this.Write("(value); }\r\n\t\t}\r\n");
            
            #line 16 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

	}
}
if(this.RealmType == RealmType.Universe) {
            
            #line default
            #line hidden
            this.Write("\t\tinternal ");
            
            #line 20 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 21 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
}
            
            #line default
            #line hidden
            
            #line 22 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
if(this.Table.Persistent) {
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprivate interface IFieldSerializer {\r\n\t\t\tbool NeedToSave(ref ");
            
            #line 25 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data);\r\n\t\t\tstring GetTextValue(ref ");
            
            #line 26 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data);\r\n\t\t\tvoid SetDefault(ref ");
            
            #line 27 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data);\r\n\t\t\tvoid SetTextValue(ref ");
            
            #line 28 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data, string text);\r\n\t\t}\r\n");
            
            #line 30 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t// Field accessors\r\n\r\n");
            
            #line 34 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

foreach(Column column in this.Table.Columns) {
	string defaultValue = (column.Default != null) ? column.Default : "default(" + column.Type + ")";
	string format;
	switch(column.Type) {
	case "string":
		format = column.IgnoreCase ? "StringComparer.OrdinalIgnoreCase.Compare({0}, {1})" : "StringComparer.Ordinal.Compare({0}, {1})";
		if(column.Default != null) {
			defaultValue = this.MakeString(defaultValue);
		} else {
			defaultValue = "null";
		}
		break;
	case "int":
		format = "Math.Sign((long){0} - (long){1})";
		break;
	case "float":
	case "double":
		format = "Math.Sign({0} - {1})";
		break;
	case "bool":
	case "Guid":
	default:
		format = "{0}.CompareTo({1})";
		break;
	}
	Func<string, string, string> compare = (l, r) => string.Format(format, l, r);

            
            #line default
            #line hidden
            this.Write("\t\t// Accessor of the ");
            
            #line 62 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" field\r\n");
            
            #line 63 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
if(column.Type == "RowId") {
            
            #line default
            #line hidden
            this.Write("\t\tpublic sealed class ");
            
            #line 64 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field : RowIdField<");
            
            #line 64 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data> {\r\n\t\t\tpublic static readonly ");
            
            #line 65 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field Field = new ");
            
            #line 65 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field();\r\n\t\t\tprivate ");
            
            #line 66 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field() : base(\"");
            
            #line 66 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("\") {}\r\n\t\t\tpublic override RowId GetValue(ref ");
            
            #line 67 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data record) {\r\n\t\t\t\treturn record.");
            
            #line 68 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tpublic override void SetValue(ref ");
            
            #line 70 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data record, RowId value) {\r\n\t\t\t\trecord.");
            
            #line 71 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t}\r\n\t\t}\r\n");
            
            #line 74 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
} else {
            
            #line default
            #line hidden
            this.Write("\t\tpublic sealed class ");
            
            #line 75 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field : IField<");
            
            #line 75 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data, ");
            
            #line 75 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(">");
            
            #line 75 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Persistent ? ", IFieldSerializer" : string.Empty));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t\t\tpublic static readonly ");
            
            #line 76 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field Field = new ");
            
            #line 76 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field();\r\n\t\t\tprivate ");
            
            #line 77 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field() {}\r\n\t\t\tpublic string Name { get { return \"");
            
            #line 78 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("\"; } }\r\n\t\t\tpublic int Order { get; set; }\r\n\t\t\tpublic ");
            
            #line 80 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" DefaultValue { get { return ");
            
            #line 80 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(defaultValue));
            
            #line default
            #line hidden
            this.Write("; } }\r\n\t\t\tpublic ");
            
            #line 81 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" GetValue(ref ");
            
            #line 81 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data record) {\r\n\t\t\t\treturn record.");
            
            #line 82 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tpublic void SetValue(ref ");
            
            #line 84 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data record, ");
            
            #line 84 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" value) {\r\n\t\t\t\trecord.");
            
            #line 85 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t}\r\n\t\t\tpublic int Compare(ref ");
            
            #line 87 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data l, ref ");
            
            #line 87 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data r) {\r\n\t\t\t\treturn ");
            
            #line 88 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(compare("l." + column.Name, "r." + column.Name)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tpublic int Compare(");
            
            #line 90 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" l, ");
            
            #line 90 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Type));
            
            #line default
            #line hidden
            this.Write(" r) {\r\n\t\t\t\treturn ");
            
            #line 91 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(compare("l", "r")));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n");
            
            #line 93 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

	if(this.Table.Persistent) {
		string parse = "text";
		switch(column.Type) {
		case "string":
			break;
		case "int":
			parse = "int.Parse(text, CultureInfo.InvariantCulture)";
			break;
		case "float":
			parse = "float.Parse(text, CultureInfo.InvariantCulture)";
			break;
		case "double":
			parse = "double.Parse(text, CultureInfo.InvariantCulture)";
			break;
		case "bool":
			parse = "bool.Parse(text)";
			break;
		case "Guid":
			parse = "new Guid(text)";
			break;
		default:
			parse = "(" + column.Type + ")Enum.Parse(typeof(" + column.Type + "), text, true)";
			break;
		}

            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t// Implementation of interface IFieldSerializer\r\n\t\t\tbool IFieldSerializer.Ne" +
                    "edToSave(ref ");
            
            #line 121 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data) {\r\n\t\t\t\treturn this.Compare(data.");
            
            #line 122 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(", this.DefaultValue) != 0;\r\n\t\t\t}\r\n\t\t\tstring IFieldSerializer.GetTextValue(ref ");
            
            #line 124 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data) {\r\n\t\t\t\treturn string.Format(CultureInfo.InvariantCulture, \"{0}\", data." +
                    "");
            
            #line 125 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t}\r\n\t\t\tvoid IFieldSerializer.SetDefault(ref ");
            
            #line 127 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data) {\r\n\t\t\t\tdata.");
            
            #line 128 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" = this.DefaultValue;\r\n\t\t\t}\r\n\t\t\tvoid IFieldSerializer.SetTextValue(ref ");
            
            #line 130 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data, string text) {\r\n\t\t\t\tdata.");
            
            #line 131 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 131 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parse));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n");
            
            #line 133 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
	}
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 135 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 137 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

}
if(this.RealmType == RealmType.Universe) {
            
            #line default
            #line hidden
            this.Write("\t\t// Special field used to access items wrapper of this record from record.\r\n\t\t//" +
                    " This is used when no other universes is used\r\n\t\tinternal sealed class ");
            
            #line 142 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Field : IField<");
            
            #line 142 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data, ");
            
            #line 142 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("> {\r\n\t\t\tpublic static readonly ");
            
            #line 143 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Field Field = new ");
            
            #line 143 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Field();\r\n\t\t\tprivate ");
            
            #line 144 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Field() {}\r\n\t\t\tpublic string Name { get { return \"");
            
            #line 145 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Wrapper\"; } }\r\n\t\t\tpublic int Order { get; set; }\r\n\t\t\tpublic ");
            
            #line 147 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(" DefaultValue { get { return null; } }\r\n\t\t\tpublic ");
            
            #line 148 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(" GetValue(ref ");
            
            #line 148 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data record) {\r\n\t\t\t\treturn record.");
            
            #line 149 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tpublic void SetValue(ref ");
            
            #line 151 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data record, ");
            
            #line 151 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(" value) {\r\n\t\t\t\trecord.");
            
            #line 152 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t}\r\n\t\t\tpublic int Compare(ref ");
            
            #line 154 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data l, ref ");
            
            #line 154 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data r) {\r\n\t\t\t\treturn this.Compare(l.");
            
            #line 155 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(", r.");
            
            #line 155 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t}\r\n\t\t\tpublic int Compare(");
            
            #line 157 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(" l, ");
            
            #line 157 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(" r) {\r\n\t\t\t\tif(object.ReferenceEquals(l, r)) return 0;\r\n\t\t\t\tif(l == null) return -" +
                    "1;\r\n\t\t\t\tif(r == null) return 1;\r\n\t\t\t\treturn l.");
            
            #line 161 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("RowId.CompareTo(r.");
            
            #line 161 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("RowId);\r\n\t\t\t}\r\n\t\t}\r\n\r\n");
            
            #line 165 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t// Creates table.\r\n\t\tpublic static TableSnapshot<");
            
            #line 167 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data> CreateTable(StoreSnapshot store) {\r\n\t\t\tTableSnapshot<");
            
            #line 168 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data> table = new TableSnapshot<");
            
            #line 168 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data>(store, \"");
            
            #line 168 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 169 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
foreach(Column column in this.Table.Columns) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t,");
            
            #line 170 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Name));
            
            #line default
            #line hidden
            this.Write("Field.Field\r\n");
            
            #line 171 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

}
if(this.RealmType == RealmType.Universe) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t,");
            
            #line 174 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Field.Field\r\n");
            
            #line 175 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t);\r\n\t\t\t// Create all but foreign keys of the table\r\n");
            
            #line 178 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

foreach(Key key in this.Table.Keys) {
	if(key.IsUnique() || key.IsIndex()) { // this will ignore only foreign keys
		string function = key.IsUnique() ? "MakeUnique" : "CreateIndex";
		if(key.KeyType == KeyType.Auto) {

            
            #line default
            #line hidden
            this.Write("\t\t\ttable.MakeAutoUnique();\r\n");
            
            #line 185 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

		} else if(key.Count == 1) {
			string primary = "";
			if(key.IsUnique()) {
				if(key.IsPrimary()) {
					primary = ", true";
				} else {
					primary = ", false";
				}
			}

            
            #line default
            #line hidden
            this.Write("\t\t\ttable.");
            
            #line 196 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 196 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Name));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 196 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data.");
            
            #line 196 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key[0].Name));
            
            #line default
            #line hidden
            this.Write("Field.Field ");
            
            #line 196 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(primary));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 197 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

		} else {

            
            #line default
            #line hidden
            this.Write("\t\t\ttable.");
            
            #line 200 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(function));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 200 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Name));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 200 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data.");
            
            #line 200 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key[0].Name));
            
            #line default
            #line hidden
            this.Write("Field.Field, ");
            
            #line 200 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data.");
            
            #line 200 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key[1].Name));
            
            #line default
            #line hidden
            this.Write("Field.Field);\r\n");
            
            #line 201 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

		}
	}
}

            
            #line default
            #line hidden
            this.Write("\t\t\t// Return created table\r\n\t\t\treturn table;\r\n\t\t}\r\n\r\n\t\t// Creates all foreign key" +
                    "s of the table\r\n\t\tpublic static void CreateForeignKeys(StoreSnapshot store) {\r\n");
            
            #line 212 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
if(this.Table.Keys.Any(k => k.IsForeign())) {
            
            #line default
            #line hidden
            this.Write("\t\t\tTableSnapshot<");
            
            #line 213 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data> table = (TableSnapshot<");
            
            #line 213 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data>)store.Table(\"");
            
            #line 213 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 214 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

foreach(Key key in this.Table.Keys) {
	if(key.IsForeign()) {

            
            #line default
            #line hidden
            this.Write("\t\t\ttable.CreateForeignKey(\"");
            
            #line 218 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Name));
            
            #line default
            #line hidden
            this.Write("\", store.Table(\"");
            
            #line 218 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.ParentName));
            
            #line default
            #line hidden
            this.Write("\"), ");
            
            #line 218 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data.");
            
            #line 218 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key[0].Name));
            
            #line default
            #line hidden
            this.Write("Field.Field, ForeignKeyAction.");
            
            #line 218 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.Action));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 218 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(key.AllowsDefault ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 219 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"

		}
	}
}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 225 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
if(this.Table.Persistent) {
            
            #line default
            #line hidden
            this.Write("\r\n\t\t// Serializer of the table\r\n\t\tpublic static void Save(TableSnapshot<");
            
            #line 228 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data> table, XmlElement root) {\r\n\t\t\tXmlDocument xml = root.OwnerDocument;\r\n\t\t\tfor" +
                    "each(RowId rowId in table.Rows) {\r\n\t\t\t\t");
            
            #line 231 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data;\r\n\t\t\t\ttable.GetData(rowId, out data);\r\n\t\t\t\tXmlElement node = xml.Create" +
                    "Element(root.Prefix, table.Name, root.NamespaceURI);\r\n\t\t\t\troot.AppendChild(node)" +
                    ";\r\n\t\t\t\tforeach(IField<");
            
            #line 235 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(@"Data> field in table.Fields) {
					IFieldSerializer serializer = field as IFieldSerializer;
					if(serializer != null && serializer.NeedToSave(ref data)) {
						XmlElement e = xml.CreateElement(root.Prefix, field.Name, root.NamespaceURI);
						node.AppendChild(e);
						e.AppendChild(xml.CreateTextNode(serializer.GetTextValue(ref data)));
					}
				}
			}
		}

		public static void Load(TableSnapshot<");
            
            #line 246 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data> table, XmlNodeList list, Action<RowId> register) {\r\n\t\t\tDictionary<string, I" +
                    "FieldSerializer> field = new Dictionary<string, IFieldSerializer>();\r\n\t\t\tforeach" +
                    "(IField<");
            
            #line 248 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(@"Data> f in table.Fields) {
				IFieldSerializer serializer = f as IFieldSerializer;
				if(serializer != null) {
					field.Add(f.Name, serializer);
				}
			}
			foreach(XmlElement node in list) {
				Debug.Assert(node.LocalName == table.Name);
				");
            
            #line 256 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write("Data data = new ");
            
            #line 256 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Table.Name));
            
            #line default
            #line hidden
            this.Write(@"Data();
				foreach(IFieldSerializer serializer in field.Values) {
					serializer.SetDefault(ref data);
				}
				foreach(XmlNode child in node.ChildNodes) {
					XmlElement c = child as XmlElement;
					IFieldSerializer serializer;
					if(c != null && c.NamespaceURI == node.NamespaceURI && field.TryGetValue(c.LocalName, out serializer)) {
						serializer.SetTextValue(ref data, c.InnerText);
					}
				}
				RowId rowId = table.Insert(ref data);
				if(register != null) {
					register(rowId);
				}
			}
		}
");
            
            #line 273 "C:\Eugene\Projects\LogicCircuit\LogicCircuit\FxCop\Sources\Tools\ItemWrapper.Generator\GeneratorTableDefinition.tt"
}
            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
