//-----------------------------------------------------------------------------
//
//	This code was generated by a ResourceWrapper.Generator Version 1.0.0.0.
//
//	Changes to this file may cause incorrect behavior and will be lost if
//	the code is regenerated.
//
//-----------------------------------------------------------------------------

namespace LogicCircuit {
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Diagnostics;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;
	using System.Runtime.CompilerServices;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated.
	// To add or remove a member, edit your .ResX file then rerun MsBuild,
	// or rebuild your VS project.
	[DebuggerNonUserCodeAttribute()]
	[CompilerGeneratedAttribute()]
	public static class SymbolShape {

		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class.
		/// </summary>
		[EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
		public static CultureInfo Culture { get; set; }

		private static ResourceManager resourceManager;

		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
		public static ResourceManager ResourceManager {
			get {
				if(resourceManager == null) {
					resourceManager = new ResourceManager("LogicCircuit.SymbolShapes.SymbolShape", typeof(SymbolShape).Assembly);
				}
				return resourceManager;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "clock.xaml".
		/// </summary>
 		public static string Clock {
			get { return ResourceManager.GetString("Clock", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "constant.xaml".
		/// </summary>
 		public static string Constant {
			get { return ResourceManager.GetString("Constant", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "led.xaml".
		/// </summary>
 		public static string Led {
			get { return ResourceManager.GetString("Led", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "ledmatrix.xaml".
		/// </summary>
 		public static string LedMatrix {
			get { return ResourceManager.GetString("LedMatrix", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "ledmatrixrectcell.xaml".
		/// </summary>
 		public static string LedMatrixRectCell {
			get { return ResourceManager.GetString("LedMatrixRectCell", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "ledmatrixroundcell.xaml".
		/// </summary>
 		public static string LedMatrixRoundCell {
			get { return ResourceManager.GetString("LedMatrixRoundCell", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "markerline.xaml".
		/// </summary>
 		public static string MarkerLine {
			get { return ResourceManager.GetString("MarkerLine", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "markerrectangle.xaml".
		/// </summary>
 		public static string MarkerRectangle {
			get { return ResourceManager.GetString("MarkerRectangle", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "pin.xaml".
		/// </summary>
 		public static string Pin {
			get { return ResourceManager.GetString("Pin", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "probe.xaml".
		/// </summary>
 		public static string Probe {
			get { return ResourceManager.GetString("Probe", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "rectangular.xaml".
		/// </summary>
 		public static string Rectangular {
			get { return ResourceManager.GetString("Rectangular", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "sevensegment.xaml".
		/// </summary>
 		public static string SevenSegment {
			get { return ResourceManager.GetString("SevenSegment", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "shapedand.xaml".
		/// </summary>
 		public static string ShapedAnd {
			get { return ResourceManager.GetString("ShapedAnd", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "shapednot.xaml".
		/// </summary>
 		public static string ShapedNot {
			get { return ResourceManager.GetString("ShapedNot", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "shapedor.xaml".
		/// </summary>
 		public static string ShapedOr {
			get { return ResourceManager.GetString("ShapedOr", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "shapedtristate.xaml".
		/// </summary>
 		public static string ShapedTriState {
			get { return ResourceManager.GetString("ShapedTriState", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "shapedxor.xaml".
		/// </summary>
 		public static string ShapedXor {
			get { return ResourceManager.GetString("ShapedXor", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "splitter.xaml".
		/// </summary>
 		public static string Splitter {
			get { return ResourceManager.GetString("Splitter", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "textnote.xaml".
		/// </summary>
 		public static string TextNote {
			get { return ResourceManager.GetString("TextNote", Culture); }
		}

		/// <summary>
		/// Looks up a localized string similar to content of the file: "toggleled.xaml".
		/// </summary>
 		public static string ToggleLed {
			get { return ResourceManager.GetString("ToggleLed", Culture); }
		}
	}
}
